sources:
  - name: "BoletimSec"
    type: "rss"
    url: "https://www.boletimsec.com.br/feed"   # confirme o feed
  - name: "Canaltech"
    type: "rss"
    url: "https://canaltech.com.br/rss/"
  - name: "Canaltech-Seguranca"
    type: "rss"
    url: "https://canaltech.com.br/rss/seguranca/"
  - name: "CISO Advisor"
    type: "rss"
    url: "https://www.cisoadvisor.com.br/feed/"
  - name: "Minuto da Segurança da Informação"
    type: "rss"
    url: "https://minutodainformacao.com.br/feed"  # confirme o feed
  - name: "Olhar Digital"
    type: "rss"
    url: "https://olhardigital.com.br/feed/"
  - name: "Security Leaders"
    type: "rss"
    url: "https://securityleaders.com.br/feed/"
  - name: "SegInfo"
    type: "rss"
    url: "https://seginfo.com.br/feed/"
  - name: "Security Report"
    type: "rss"
    url: "https://www.securityreport.com.br/feed/"
  - name: "TI Inside Online"
    type: "rss"
    url: "https://tiinside.com.br/feed/"
